### ISSUE TITLE
请问php该怎么使用。。。我不懂java，你能告诉我原理吗。

### ISSUE THREAD

**Issue by javascriptdeecho** [wangyiidii/laboratory-v2#1]
请问php该怎么使用。。。我不懂java，你能告诉我原理吗。
我大概看到了，你就是获取了重定向的地址。然后再获取重定向的html。

但是，我使用过php获取。是没有办法得到js渲染后的内容的，而且还会出现验证码。

你能说一下你的解决思路吗

谢

**Comment by aa24615** [comment]
> 

php版  https://github.com/aa24615/douyin

**Comment by wangyiidii** [comment]
> 请问php该怎么使用。。。我不懂java，你能告诉我原理吗。 我大概看到了，你就是获取了重定向的地址。然后再获取重定向的html。
> 
> 但是，我使用过php获取。是没有办法得到js渲染后的内容的，而且还会出现验证码。
> 
> 你能说一下你的解决思路吗
> 
> 谢


方案一：
使用 @aa24615 的方案，应该是app抓的接口，请求短链，获取响应的Location中的id，然后通过接口 https://www.iesdouyin.com/aweme/v1/web/aweme/detail/?aweme_id=去请求获取json数据即可

**Comment by aa24615** [comment]
你直接看代码啊发自我的 iPhone在 2023年1月10日，10:38，wangyiidii ***@***.***> 写道：﻿
Closed #1 as completed.
